"""
extract_geometry — read the EXACT computed geometry for every model from the
spreadsheet's geometry sheet, by selecting each model in turn.

This produces a ground-truth geometry table so the library doesn't need
per-model override guesswork. Output is written as a Python dict literal
that can be pasted into wcac/models.py.

The geometry named ranges (verified):
  Nt     = geometry!F6    tube count
  Lteff  = geometry!F11   effective tube length (m)
  A      = geometry!F23   heat transfer area (m²)
  Acs    = geometry!F18   shell crossflow area (m²)
  Act    = geometry!F31   tube flow area (m²)
  Lbe    = geometry!F24   end zone gap (m)
  Lbc    = models!E26     central baffle gap (m)
  Ntcc   = geometry!F16   crossflow rows
  Ntcw   = geometry!F17   window rows
  Jc     = geometry!F34   segmental baffle correction
  Jl     = geometry!F35   leakage correction
  Abas   = geometry!F19   bundle bypass area
  Asb    = geometry!F25   shell-baffle bypass
  Abt    = geometry!F26   baffle-tube bypass
  Acse   = geometry!F27   end-zone crossflow area
  Acsn   = geometry!F28   nozzle area
  Nb     = models!E22     baffle count
"""
import sys, os
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..', '..'))

from .xl_driver import SpreadsheetOracle, XLScenario, INPUT_CELLS
from wcac.models import list_models


# Geometry quantities to extract (name -> (sheet, cell))
GEOM_CELLS = {
    'Nt':    ('geometry', 'F6'),
    'Lteff': ('geometry', 'F11'),
    'A':     ('geometry', 'F23'),
    'Acs':   ('geometry', 'F18'),
    'Act':   ('geometry', 'F31'),
    'Lbe':   ('geometry', 'F24'),
    'Lbc':   ('models',   'E26'),
    'Ntcc':  ('geometry', 'F16'),
    'Ntcw':  ('geometry', 'F17'),
    'Jc':    ('geometry', 'F34'),
    'Jl':    ('geometry', 'F35'),
    'Abas':  ('geometry', 'F19'),
    'Asb':   ('geometry', 'F25'),
    'Abt':   ('geometry', 'F26'),
    'Acse':  ('geometry', 'F27'),
    'Acsn':  ('geometry', 'F28'),
    'Acw':   ('geometry', 'F21'),
    'Dhw':   ('geometry', 'F22'),
    'rctl':  ('geometry', 'F7'),
    'rotl':  ('geometry', 'F8'),
    'Nb':    ('models',   'E22'),
    'sigmat':('geometry', 'F32'),
    # Bell-Delaware pressure-drop correction factors (geometry-only; flow-independent)
    'Rl':    ('geometry', 'F42'),   # baffle leakage correction, pressure loss
    'Rb':    ('geometry', 'F43'),   # bundle bypass correction, pressure loss
    'Rs':    ('geometry', 'F45'),   # end zone correction, pressure loss
}


CONFIGS = [
    ('Fixed', 300), ('Fixed', 200),
    ('Removable', 300), ('Removable', 200),
]


def extract_all():
    """Extract geometry for all models × all 4 (bundle, pressure) configs.
    Returns dict[(bundle, dp)] -> dict[model] -> dict[quantity].
    """
    out = {cfg: {} for cfg in CONFIGS}
    with SpreadsheetOracle() as oracle:
        d = oracle._wb.sheets['design']
        for bundle, dp in CONFIGS:
            print(f'\n=== {bundle} / {dp} psig ===')
            for model in list_models():
                d.range(INPUT_CELLS['model']).value = model
                d.range(INPUT_CELLS['bundle_type']).value = bundle
                d.range(INPUT_CELLS['tube_design_pressure']).value = dp
                oracle._app.api.CalculateFull()
                geom = {}
                for name, (sheet, cell) in GEOM_CELLS.items():
                    geom[name] = oracle._wb.sheets[sheet].range(cell).value
                out[(bundle, dp)][model] = geom
            print(f'  {len(list_models())} models extracted')
    return out


def write_table(data, path):
    """Write extracted geometry as a Python nested dict literal."""
    with open(path, 'w', encoding='utf-8') as f:
        f.write('"""\n')
        f.write('EXACT_GEOMETRY — ground-truth geometry extracted from the W1279\n')
        f.write('spreadsheet geometry sheet for every model and configuration.\n')
        f.write('All values in SI (metres, m², dimensionless). Auto-generated by\n')
        f.write('tests/spreadsheet/extract_geometry.py — do not edit by hand.\n\n')
        f.write('Keyed by (bundle_type, design_pressure_psig) then model code.\n')
        f.write('"""\n\n')
        f.write('EXACT_GEOMETRY = {\n')
        for cfg, models in data.items():
            f.write(f'    {cfg!r}: {{\n')
            for model, geom in models.items():
                f.write(f'        {model!r}: {{')
                items = ', '.join(f'{k!r}: {v!r}' for k, v in geom.items())
                f.write(items)
                f.write('},\n')
            f.write('    },\n')
        f.write('}\n')
    n = sum(len(m) for m in data.values())
    print(f'\nWrote {n} model-configs to {path}')


if __name__ == '__main__':
    print('Extracting exact geometry for 34 models × 4 configs from the spreadsheet...')
    data = extract_all()
    out_path = os.path.join(os.path.dirname(__file__), '..', '..', 'wcac', 'exact_geometry.py')
    write_table(data, os.path.abspath(out_path))
