[build]
  publish = "."
  functions = "netlify/functions"
  command = "npm run build:css"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200
